# 220929
set(source_dir ${CMAKE_SOURCE_DIR}/external/boringssl)

# libcrypto
#add_subdirectory( ${source_dir}/src)
add_library(crypto
  ${source_dir}/src/crypto/asn1/a_bitstr.cc
  ${source_dir}/src/crypto/asn1/a_bool.cc
  ${source_dir}/src/crypto/asn1/a_d2i_fp.cc
  ${source_dir}/src/crypto/asn1/a_dup.cc
  ${source_dir}/src/crypto/asn1/a_gentm.cc
  ${source_dir}/src/crypto/asn1/a_i2d_fp.cc
  ${source_dir}/src/crypto/asn1/a_int.cc
  ${source_dir}/src/crypto/asn1/a_mbstr.cc
  ${source_dir}/src/crypto/asn1/a_object.cc
  ${source_dir}/src/crypto/asn1/a_octet.cc
  ${source_dir}/src/crypto/asn1/a_strex.cc
  ${source_dir}/src/crypto/asn1/a_strnid.cc
  ${source_dir}/src/crypto/asn1/a_time.cc
  ${source_dir}/src/crypto/asn1/a_type.cc
  ${source_dir}/src/crypto/asn1/a_utctm.cc
  ${source_dir}/src/crypto/asn1/asn1_lib.cc
  ${source_dir}/src/crypto/asn1/asn1_par.cc
  ${source_dir}/src/crypto/asn1/asn_pack.cc
  ${source_dir}/src/crypto/asn1/f_int.cc
  ${source_dir}/src/crypto/asn1/f_string.cc
  ${source_dir}/src/crypto/asn1/posix_time.cc
  ${source_dir}/src/crypto/asn1/tasn_dec.cc
  ${source_dir}/src/crypto/asn1/tasn_enc.cc
  ${source_dir}/src/crypto/asn1/tasn_fre.cc
  ${source_dir}/src/crypto/asn1/tasn_new.cc
  ${source_dir}/src/crypto/asn1/tasn_typ.cc
  ${source_dir}/src/crypto/asn1/tasn_utl.cc
  ${source_dir}/src/crypto/base64/base64.cc
  ${source_dir}/src/crypto/bio/bio.cc
  ${source_dir}/src/crypto/bio/bio_mem.cc
  ${source_dir}/src/crypto/bio/connect.cc
  ${source_dir}/src/crypto/bio/errno.cc
  ${source_dir}/src/crypto/bio/fd.cc
  ${source_dir}/src/crypto/bio/file.cc
  ${source_dir}/src/crypto/bio/hexdump.cc
  ${source_dir}/src/crypto/bio/pair.cc
  ${source_dir}/src/crypto/bio/printf.cc
  ${source_dir}/src/crypto/bio/socket.cc
  ${source_dir}/src/crypto/bio/socket_helper.cc
  ${source_dir}/src/crypto/blake2/blake2.cc
  ${source_dir}/src/crypto/bn_extra/bn_asn1.cc
  ${source_dir}/src/crypto/bn_extra/convert.cc
  ${source_dir}/src/crypto/buf/buf.cc
  ${source_dir}/src/crypto/bytestring/asn1_compat.cc
  ${source_dir}/src/crypto/bytestring/ber.cc
  ${source_dir}/src/crypto/bytestring/cbb.cc
  ${source_dir}/src/crypto/bytestring/cbs.cc
  ${source_dir}/src/crypto/bytestring/unicode.cc
  ${source_dir}/src/crypto/chacha/chacha.cc
  ${source_dir}/src/crypto/cipher_extra/cipher_extra.cc
  ${source_dir}/src/crypto/cipher_extra/derive_key.cc
  ${source_dir}/src/crypto/cipher_extra/e_aesctrhmac.cc
  ${source_dir}/src/crypto/cipher_extra/e_aesgcmsiv.cc
  ${source_dir}/src/crypto/cipher_extra/e_chacha20poly1305.cc
  ${source_dir}/src/crypto/cipher_extra/e_des.cc
  ${source_dir}/src/crypto/cipher_extra/e_null.cc
  ${source_dir}/src/crypto/cipher_extra/e_rc2.cc
  ${source_dir}/src/crypto/cipher_extra/e_rc4.cc
  ${source_dir}/src/crypto/cipher_extra/e_tls.cc
  ${source_dir}/src/crypto/cipher_extra/tls_cbc.cc
  ${source_dir}/src/crypto/conf/conf.cc
  ${source_dir}/src/crypto/cpu_aarch64_apple.cc
  ${source_dir}/src/crypto/cpu_aarch64_fuchsia.cc
  ${source_dir}/src/crypto/cpu_aarch64_linux.cc
  ${source_dir}/src/crypto/cpu_aarch64_openbsd.cc
  ${source_dir}/src/crypto/cpu_aarch64_sysreg.cc
  ${source_dir}/src/crypto/cpu_aarch64_win.cc
  ${source_dir}/src/crypto/cpu_arm_freebsd.cc
  ${source_dir}/src/crypto/cpu_arm_linux.cc
  ${source_dir}/src/crypto/cpu_intel.cc
  ${source_dir}/src/crypto/crypto.cc
  ${source_dir}/src/crypto/curve25519/curve25519.cc
  ${source_dir}/src/crypto/curve25519/curve25519_64_adx.cc
  ${source_dir}/src/crypto/curve25519/spake25519.cc
  ${source_dir}/src/crypto/des/des.cc
  ${source_dir}/src/crypto/dh_extra/dh_asn1.cc
  ${source_dir}/src/crypto/dh_extra/params.cc
  ${source_dir}/src/crypto/digest_extra/digest_extra.cc
  ${source_dir}/src/crypto/dsa/dsa.cc
  ${source_dir}/src/crypto/dsa/dsa_asn1.cc
  ${source_dir}/src/crypto/ec_extra/ec_asn1.cc
  ${source_dir}/src/crypto/ec_extra/ec_derive.cc
  ${source_dir}/src/crypto/ec_extra/hash_to_curve.cc
  ${source_dir}/src/crypto/ecdh_extra/ecdh_extra.cc
  ${source_dir}/src/crypto/ecdsa_extra/ecdsa_asn1.cc
  ${source_dir}/src/crypto/engine/engine.cc
  ${source_dir}/src/crypto/err/err.cc
  ${source_dir}/src/crypto/evp/evp.cc
  ${source_dir}/src/crypto/evp/evp_asn1.cc
  ${source_dir}/src/crypto/evp/evp_ctx.cc
  ${source_dir}/src/crypto/evp/p_dh.cc
  ${source_dir}/src/crypto/evp/p_dh_asn1.cc
  ${source_dir}/src/crypto/evp/p_dsa_asn1.cc
  ${source_dir}/src/crypto/evp/p_ec.cc
  ${source_dir}/src/crypto/evp/p_ec_asn1.cc
  ${source_dir}/src/crypto/evp/p_ed25519.cc
  ${source_dir}/src/crypto/evp/p_ed25519_asn1.cc
  ${source_dir}/src/crypto/evp/p_hkdf.cc
  ${source_dir}/src/crypto/evp/p_rsa.cc
  ${source_dir}/src/crypto/evp/p_rsa_asn1.cc
  ${source_dir}/src/crypto/evp/p_x25519.cc
  ${source_dir}/src/crypto/evp/p_x25519_asn1.cc
  ${source_dir}/src/crypto/evp/pbkdf.cc
  ${source_dir}/src/crypto/evp/print.cc
  ${source_dir}/src/crypto/evp/scrypt.cc
  ${source_dir}/src/crypto/evp/sign.cc
  ${source_dir}/src/crypto/ex_data.cc
  ${source_dir}/src/crypto/fipsmodule/bcm.cc
  ${source_dir}/src/crypto/fipsmodule/fips_shared_support.cc
  ${source_dir}/src/crypto/hpke/hpke.cc
  ${source_dir}/src/crypto/hrss/hrss.cc
  ${source_dir}/src/crypto/kyber/kyber.cc
  ${source_dir}/src/crypto/lhash/lhash.cc
  ${source_dir}/src/crypto/md4/md4.cc
  ${source_dir}/src/crypto/md5/md5.cc
  ${source_dir}/src/crypto/mem.cc
  ${source_dir}/src/crypto/mldsa/mldsa.cc
  ${source_dir}/src/crypto/mlkem/mlkem.cc
  ${source_dir}/src/crypto/obj/obj.cc
  ${source_dir}/src/crypto/obj/obj_xref.cc
  ${source_dir}/src/crypto/pem/pem_all.cc
  ${source_dir}/src/crypto/pem/pem_info.cc
  ${source_dir}/src/crypto/pem/pem_lib.cc
  ${source_dir}/src/crypto/pem/pem_oth.cc
  ${source_dir}/src/crypto/pem/pem_pk8.cc
  ${source_dir}/src/crypto/pem/pem_pkey.cc
  ${source_dir}/src/crypto/pem/pem_x509.cc
  ${source_dir}/src/crypto/pem/pem_xaux.cc
  ${source_dir}/src/crypto/pkcs7/pkcs7.cc
  ${source_dir}/src/crypto/pkcs7/pkcs7_x509.cc
  ${source_dir}/src/crypto/pkcs8/p5_pbev2.cc
  ${source_dir}/src/crypto/pkcs8/pkcs8.cc
  ${source_dir}/src/crypto/pkcs8/pkcs8_x509.cc
  ${source_dir}/src/crypto/poly1305/poly1305.cc
  ${source_dir}/src/crypto/poly1305/poly1305_arm.cc
  ${source_dir}/src/crypto/poly1305/poly1305_vec.cc
  ${source_dir}/src/crypto/pool/pool.cc
  ${source_dir}/src/crypto/rand_extra/deterministic.cc
  ${source_dir}/src/crypto/rand_extra/fork_detect.cc
  ${source_dir}/src/crypto/rand_extra/forkunsafe.cc
  ${source_dir}/src/crypto/rand_extra/getentropy.cc
  ${source_dir}/src/crypto/rand_extra/ios.cc
  ${source_dir}/src/crypto/rand_extra/passive.cc
  ${source_dir}/src/crypto/rand_extra/rand_extra.cc
  ${source_dir}/src/crypto/rand_extra/trusty.cc
  ${source_dir}/src/crypto/rand_extra/urandom.cc
  ${source_dir}/src/crypto/rand_extra/windows.cc
  ${source_dir}/src/crypto/rc4/rc4.cc
  ${source_dir}/src/crypto/refcount.cc
  ${source_dir}/src/crypto/rsa_extra/rsa_asn1.cc
  ${source_dir}/src/crypto/rsa_extra/rsa_crypt.cc
  ${source_dir}/src/crypto/rsa_extra/rsa_extra.cc
  ${source_dir}/src/crypto/rsa_extra/rsa_print.cc
  ${source_dir}/src/crypto/sha/sha1.cc
  ${source_dir}/src/crypto/sha/sha256.cc
  ${source_dir}/src/crypto/sha/sha512.cc
  ${source_dir}/src/crypto/siphash/siphash.cc
  ${source_dir}/src/crypto/slhdsa/slhdsa.cc
  ${source_dir}/src/crypto/spake2plus/spake2plus.cc
  ${source_dir}/src/crypto/stack/stack.cc
  ${source_dir}/src/crypto/thread.cc
  ${source_dir}/src/crypto/thread_none.cc
  ${source_dir}/src/crypto/thread_pthread.cc
  ${source_dir}/src/crypto/thread_win.cc
  ${source_dir}/src/crypto/trust_token/pmbtoken.cc
  ${source_dir}/src/crypto/trust_token/trust_token.cc
  ${source_dir}/src/crypto/trust_token/voprf.cc
  ${source_dir}/src/crypto/x509/a_digest.cc
  ${source_dir}/src/crypto/x509/a_sign.cc
  ${source_dir}/src/crypto/x509/a_verify.cc
  ${source_dir}/src/crypto/x509/algorithm.cc
  ${source_dir}/src/crypto/x509/asn1_gen.cc
  ${source_dir}/src/crypto/x509/by_dir.cc
  ${source_dir}/src/crypto/x509/by_file.cc
  ${source_dir}/src/crypto/x509/i2d_pr.cc
  ${source_dir}/src/crypto/x509/name_print.cc
  ${source_dir}/src/crypto/x509/policy.cc
  ${source_dir}/src/crypto/x509/rsa_pss.cc
  ${source_dir}/src/crypto/x509/t_crl.cc
  ${source_dir}/src/crypto/x509/t_req.cc
  ${source_dir}/src/crypto/x509/t_x509.cc
  ${source_dir}/src/crypto/x509/t_x509a.cc
  ${source_dir}/src/crypto/x509/v3_akey.cc
  ${source_dir}/src/crypto/x509/v3_akeya.cc
  ${source_dir}/src/crypto/x509/v3_alt.cc
  ${source_dir}/src/crypto/x509/v3_bcons.cc
  ${source_dir}/src/crypto/x509/v3_bitst.cc
  ${source_dir}/src/crypto/x509/v3_conf.cc
  ${source_dir}/src/crypto/x509/v3_cpols.cc
  ${source_dir}/src/crypto/x509/v3_crld.cc
  ${source_dir}/src/crypto/x509/v3_enum.cc
  ${source_dir}/src/crypto/x509/v3_extku.cc
  ${source_dir}/src/crypto/x509/v3_genn.cc
  ${source_dir}/src/crypto/x509/v3_ia5.cc
  ${source_dir}/src/crypto/x509/v3_info.cc
  ${source_dir}/src/crypto/x509/v3_int.cc
  ${source_dir}/src/crypto/x509/v3_lib.cc
  ${source_dir}/src/crypto/x509/v3_ncons.cc
  ${source_dir}/src/crypto/x509/v3_ocsp.cc
  ${source_dir}/src/crypto/x509/v3_pcons.cc
  ${source_dir}/src/crypto/x509/v3_pmaps.cc
  ${source_dir}/src/crypto/x509/v3_prn.cc
  ${source_dir}/src/crypto/x509/v3_purp.cc
  ${source_dir}/src/crypto/x509/v3_skey.cc
  ${source_dir}/src/crypto/x509/v3_utl.cc
  ${source_dir}/src/crypto/x509/x509.cc
  ${source_dir}/src/crypto/x509/x509_att.cc
  ${source_dir}/src/crypto/x509/x509_cmp.cc
  ${source_dir}/src/crypto/x509/x509_d2.cc
  ${source_dir}/src/crypto/x509/x509_def.cc
  ${source_dir}/src/crypto/x509/x509_ext.cc
  ${source_dir}/src/crypto/x509/x509_lu.cc
  ${source_dir}/src/crypto/x509/x509_obj.cc
  ${source_dir}/src/crypto/x509/x509_req.cc
  ${source_dir}/src/crypto/x509/x509_set.cc
  ${source_dir}/src/crypto/x509/x509_trs.cc
  ${source_dir}/src/crypto/x509/x509_txt.cc
  ${source_dir}/src/crypto/x509/x509_v3.cc
  ${source_dir}/src/crypto/x509/x509_vfy.cc
  ${source_dir}/src/crypto/x509/x509_vpm.cc
  ${source_dir}/src/crypto/x509/x509cset.cc
  ${source_dir}/src/crypto/x509/x509name.cc
  ${source_dir}/src/crypto/x509/x509rset.cc
  ${source_dir}/src/crypto/x509/x509spki.cc
  ${source_dir}/src/crypto/x509/x_algor.cc
  ${source_dir}/src/crypto/x509/x_all.cc
  ${source_dir}/src/crypto/x509/x_attrib.cc
  ${source_dir}/src/crypto/x509/x_crl.cc
  ${source_dir}/src/crypto/x509/x_exten.cc
  ${source_dir}/src/crypto/x509/x_name.cc
  ${source_dir}/src/crypto/x509/x_pubkey.cc
  ${source_dir}/src/crypto/x509/x_req.cc
  ${source_dir}/src/crypto/x509/x_sig.cc
  ${source_dir}/src/crypto/x509/x_spki.cc
  ${source_dir}/src/crypto/x509/x_val.cc
  ${source_dir}/src/crypto/x509/x_x509.cc
  ${source_dir}/src/crypto/x509/x_x509a.cc
  ${source_dir}/src/gen/crypto/err_data.cc
)
target_include_directories(crypto PRIVATE
         ${source_dir}/src/include)
